import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { AuthProvider } from "./context/AuthContext";


export const metadata: Metadata = {
  title: "matbaarehberi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider> 
        <Header/>
       <div className="flex flex-col min-h-screen">{children}</div>
        <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
